# Generated by Django 5.2.1 on 2025-05-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pc', 'Piece'), ('kg', 'Kilogram'), ('box', 'Box')], default='pc', max_length=10),
        ),
    ]
