# Generated by Django 5.2.1 on 2025-05-13 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='status',
        ),
        migrations.AlterField(
            model_name='requisition',
            name='expected_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='priority',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
