# Generated by Django 5.2.1 on 2025-05-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_remove_requisition_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisitionitem',
            old_name='product',
            new_name='item_name',
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
