# Generated by Django 5.2.1 on 2025-05-13 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0002_product_unit'),
        ('purchase', '0003_rename_product_requisitionitem_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_items_by_name', to='core_settings.product'),
        ),
    ]
