# Generated by Django 5.2.1 on 2025-05-13 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0002_product_unit'),
        ('purchase', '0004_alter_requisitionitem_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='priority',
            field=models.CharField(default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_items', to='core_settings.product'),
        ),
    ]
