# Generated by Django 5.2.1 on 2025-05-15 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0002_product_unit'),
        ('purchase', '0005_alter_requisition_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='core_settings.department'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_no',
            field=models.CharField(blank=True, editable=False, help_text='Automatically generated requisition number.', max_length=20, null=True, unique=True),
        ),
    ]
