# Generated by Django 5.2.1 on 2025-05-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_requisition_approved_by_requisition_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisition',
            options={'permissions': [('can_approve_requisition', 'Can approve requisition')]},
        ),
    ]
