# Generated by Django 5.2.1 on 2025-05-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_alter_requisition_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisition',
            options={'permissions': [('can_approve_requisition', 'Can approve requisition'), ('can_view_approved_requisition', 'Can view approved requisitions')]},
        ),
    ]
