# Generated by Django 5.2.1 on 2025-05-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_vendor_alter_requisition_requisition_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DONE', 'done')], default='PENDING', max_length=10),
        ),
    ]
