# Generated by Django 5.2.1 on 2025-05-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_purchaseorder_discount_purchaseorder_vat_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisition',
            options={'permissions': [('can_approve_requisition', 'Can approve requisition'), ('can_view_approved_requisition', 'Can view approved requisitions'), ('can_view_purchaseorder', 'Can view purchase order')]},
        ),
    ]
