# Generated by Django 5.2.1 on 2025-07-03 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalinsurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('min_age', models.PositiveIntegerField()),
                ('max_age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DurationBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('min_days', models.PositiveIntegerField()),
                ('max_days', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='digitalinsurance.product')),
            ],
        ),
        migrations.CreateModel(
            name='TravelPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_type', models.CharField(max_length=100)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purposes', to='digitalinsurance.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('no_cover', models.BooleanField(default=False)),
                ('age_band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalinsurance.ageband')),
                ('duration_band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalinsurance.durationband')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premiums', to='digitalinsurance.travelpurpose')),
            ],
            options={
                'unique_together': {('purpose', 'age_band', 'duration_band')},
            },
        ),
    ]
