# Generated by Django 5.2.1 on 2025-07-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalinsurance', '0002_ageband_durationband_plan_travelpurpose_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='TK', max_length=10),
        ),
    ]
