# Generated by Django 5.2.1 on 2025-07-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalinsurance', '0003_alter_plan_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premium',
            options={'ordering': ['purpose', 'age_band', 'duration_band'], 'verbose_name': 'Premium', 'verbose_name_plural': 'Premiums'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(choices=[('BDT', 'Taka (৳)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)')], default='BDT', max_length=10),
        ),
    ]
