# Generated by Django 5.2.1 on 2025-07-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalinsurance', '0004_alter_premium_options_alter_plan_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='currency',
        ),
        migrations.AddField(
            model_name='premium',
            name='currency',
            field=models.CharField(choices=[('BDT', 'Taka (৳)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)')], default='BDT', max_length=10),
        ),
    ]
