# Generated by Django 5.2.1 on 2025-07-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalinsurance', '0005_remove_plan_currency_premium_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
    ]
