# Generated by Django 5.2.1 on 2025-07-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalinsurance', '0007_customerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='kyc/docs/'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/photos/'),
        ),
    ]
