# Generated by Django 5.2.1 on 2025-07-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalinsurance', '0009_insurancepolicy_policydata_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='transaction_method',
            field=models.CharField(default='SSLCommerz', max_length=50),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='transaction_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
