# Generated by Django 5.2.1 on 2025-05-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edocuments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edocument',
            options={'permissions': [('can_view_document', 'Can view documents'), ('can_approve_document', 'Can approve documents'), ('can_upload_document', 'Can upload documents')]},
        ),
    ]
