# Generated by Django 5.2.1 on 2025-05-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
